### PR TITLE
add Bloomerang::Campaign

### PR DESCRIPTION
**Pull request by chiperific**
with all, show, update and create

### CODE REVIEW

**Comment by chiperific** [comment]
I would like to add the missing models to your gem. My priorities are Interactions, Notes, and Emails, but I'd like your gem to have 90% of the API capabilities and I'm willing to write the commits.

If you're interested, I'd also be willing to add Models so we could instantiate the JSON responses into objects.

**Comment by chiperific** [comment]
relies on PR #2 for Bloomerang::Base#put

**Comment by allynfolksjr** [comment]
@chiperific Hi! I had planned on reviewing these contributions today: sometimes things are a bit slow in being reviewed. If you're still interested in getting this merged in I'm happy to give it a look.

**Comment by chiperific** [comment]
Hi! I started spinning off my own gem from the fork, so it's your call. I thought your unpublished gem was a pretty specific use case for your site and you may not really want all the other endpoints anyway.

**Comment by chiperific** [comment]
The [gem is published](https://rubygems.org/gems/bloomerang_api) and I tried to give you [sufficient credit](https://github.com/chiperific/bloomerang_api#bloomerang) for the initial lift, but let me know if you'd rather have some other attribution/credit.

**Pull request closed without merging**
